using Application.Features.Medicines.Dtos;
using Domain.Entities.Inventory;
using Domain.Enums;

namespace Application.Features.Inventory.Dtos;

public static class InventoryMapping
{
    /// <summary>
    /// Converts a <see cref="ReceiveInventoryRequest"/> into the shared
    /// <see cref="AddBatchRequest"/> used by the batch-creation command, so the
    /// Adjust Stock "Receive" flow and the Medicines-screen "Add Batch" flow share
    /// one command/handler and cannot drift apart.
    /// </summary>
    public static AddBatchRequest ToAddBatchRequest(this ReceiveInventoryRequest request)
        => new()
        {
            MedicineVariantId = request.MedicineVariantId,
            // BatchNumber intentionally omitted � generated by the AddBatch flow.
            ManufactureDate = request.ManufactureDate,
            ExpiryDate = request.ExpiryDate,
            PackagesReceived = request.PackagesReceived,
            UnitCost = request.UnitCost,
            SupplierName = request.SupplierName
        };

    /// <summary>
    /// Builds an <see cref="InventoryAdjustment"/> from the request. The caller
    /// supplies the batch stock level BEFORE the change (<paramref name="quantityBefore"/>)
    /// so the record captures an accurate before/after snapshot. The timestamp is
    /// always the current UTC time (normalized to UTC inside the entity).
    /// </summary>
    private const int CriticalWithinDays = 30;
    private const int WarningWithinDays = 90;

    /// <summary>Maps a low-stock projection row (display name built here).</summary>
    public static LowStockDto ToDto(this LowStockRow r)
        => new(
            r.MedicineId,
            r.MedicineName,
            r.MedicineNameAr,
            r.MedicineVariantId,
            $"{r.Form} {r.Strength} {r.Unit}",
            r.AvailableQuantity,
            r.ReorderLevel,
            r.Form,
            r.Unit,
            r.Strength);

    /// <summary>Maps a summary projection row (stock status derived here).</summary>
    public static MedicineInventorySummaryDto ToDto(this MedicineInventorySummaryRow r)
        => new(
            r.Id,
            r.Name,
            r.NameAr,
            r.GenericName,
            r.GenericNameAr,
            r.VariantCount,
            r.TotalQuantity,
            r.ReorderLevel,
            GetStockStatus(r.TotalQuantity, r.HasLowVariant),
            r.NearestExpiryDate,
            r.ActiveBatchCount);

    /// <summary>Maps an expiry-alert projection row (display name + status derived here).</summary>
    public static ExpiryAlertDto ToDto(this ExpiryAlertRow r)
        => new(
            r.BatchId,
            r.MedicineName,
            r.MedicineNameAr,
            r.Strength is null ? $"{r.Form} {r.Unit}".Trim() : $"{r.Form} {r.Strength} {r.Unit}",
            r.BatchNumber,
            r.ExpiryDate,
            r.DaysToExpiry,
            r.RemainingQuantity,
            GetExpiryStatus(r.DaysToExpiry));

    /// <summary>Maps an adjustment projection row (display name + adjuster name applied here).</summary>
    public static InventoryAdjustmentDto ToDto(this InventoryAdjustmentRow r, string? adjustedByName)
        => new(
            r.Id,
            r.MedicineBatchId,
            r.MedicineName,
            r.MedicineNameAr,
            r.Strength is null ? $"{r.Form} {r.Unit}".Trim() : $"{r.Form} {r.Strength} {r.Unit}",
            r.BatchNumber,
            r.Type.ToString(),
            r.QuantityChanged,
            r.QuantityBefore,
            r.QuantityAfter,
            r.Reason,
            r.AdjustedBy,
            adjustedByName,
            r.AdjustedAt);

    private static string GetStockStatus(int totalQuantity, bool hasLowVariant)
        => totalQuantity == 0
            ? InventoryStatus.OutOfStock
            : hasLowVariant
                ? InventoryStatus.LowStock
                : InventoryStatus.InStock;

    private static string GetExpiryStatus(int daysToExpiry)
        => daysToExpiry < 0
            ? ExpiryStatus.Expired
            : daysToExpiry < CriticalWithinDays
                ? ExpiryStatus.Critical
                : daysToExpiry < WarningWithinDays
                    ? ExpiryStatus.Warning
                    : ExpiryStatus.Safe;

    public static InventoryAdjustment ToEntity(this AdjustInventoryRequest request, Guid medicineBatchId,
        Guid? adjustedBy, int quantityBefore, int quantityAfter)
    {
        var isIncrease = request.Type is InventoryAdjustmentType.Increase or InventoryAdjustmentType.Returned
            or InventoryAdjustmentType.TransferIn;
        var delta = isIncrease ? request.Quantity : -request.Quantity;

        return new InventoryAdjustment(
            medicineBatchId,
            request.Type,
            delta,
            request.Reason,
            adjustedBy,
            quantityBefore,
            quantityAfter,
            DateTime.UtcNow);
    }

    /// <summary>
    /// Builds the audit <see cref="InventoryAdjustment"/> for a newly created
    /// batch. The caller computes <paramref name="quantityChanged"/> (sign must
    /// match <see cref="AddBatchRequest.AdjustmentType"/>) and supplies the
    /// before/after snapshot; the timestamp is always the current UTC time.
    /// </summary>
    public static InventoryAdjustment ToEntity(
        this AddBatchRequest request,
        Guid batchId,
        int quantityChanged,
        Guid? adjustedBy,
        int quantityBefore,
        int quantityAfter,
        string reason)
        => new(
            batchId,
            request.AdjustmentType,
            quantityChanged,
            reason,
            adjustedBy,
            quantityBefore,
            quantityAfter,
            DateTime.UtcNow);
}