using Application.Features.Medicines.Dtos;
using Domain.Entities.Inventory;
using Domain.Enums;

namespace Application.Features.Inventory.Dtos;

public static class InventoryMapping
{
    /// <summary>
    /// Converts a <see cref="ReceiveInventoryRequest"/> into the shared
    /// <see cref="AddBatchRequest"/> used by the batch-creation command, so the
    /// Adjust Stock "Receive" flow and the Medicines-screen "Add Batch" flow share
    /// one command/handler and cannot drift apart.
    /// </summary>
    public static AddBatchRequest ToAddBatchRequest(this ReceiveInventoryRequest request)
        => new()
        {
            MedicineVariantId = request.MedicineVariantId,
            // BatchNumber intentionally omitted — generated by the AddBatch flow.
            ManufactureDate = request.ManufactureDate,
            ExpiryDate = request.ExpiryDate,
            PackagesReceived = request.PackagesReceived,
            UnitCost = request.UnitCost,
            SupplierName = request.SupplierName
        };

    /// <summary>
    /// Builds an <see cref="InventoryAdjustment"/> from the request. The caller
    /// supplies the batch stock level BEFORE the change (<paramref name="quantityBefore"/>)
    /// so the record captures an accurate before/after snapshot. The timestamp is
    /// always the current UTC time (normalized to UTC inside the entity).
    /// </summary>
    public static InventoryAdjustment ToEntity(this AdjustInventoryRequest request, Guid medicineBatchId,
        Guid? adjustedBy, int quantityBefore, int quantityAfter)
    {
        var isIncrease = request.Type is InventoryAdjustmentType.Increase or InventoryAdjustmentType.Returned
            or InventoryAdjustmentType.TransferIn;
        var delta = isIncrease ? request.Quantity : -request.Quantity;

        return new InventoryAdjustment(
            medicineBatchId,
            request.Type,
            delta,
            request.Reason,
            adjustedBy,
            quantityBefore,
            quantityAfter,
            DateTime.UtcNow);
    }
}